test_that("heterogeneous inventory adapter matches the spot Rcpp accounting result", {
  expected <- sim_spot_step(list(cash = 1000, units = 0, avg_cost = NA_real_),
    close = 100, signed_qty = 5, execution_price = 100, contract_size = 1, fee_rt = .01)
  exchange <- sim_exchange_new(list(cash = 1000, fee_rt = .01))
  sim_asset_add(exchange, "SPY", asset_id = 1L, instrument_profile = "equity")
  day1 <- as.POSIXct("2025-01-01", tz = "UTC")
  sim_exchange_place_order(exchange, "alice", day1, symbol = "SPY", side = "buy", qty = 5)
  bar <- data.frame(timestamp = day1, symbol = "SPY", asset_id = 1L, open = 100, high = 101, low = 99, close = 100)
  sim_exchange_step(exchange, bar)
  sim_exchange_step(exchange, transform(bar, timestamp = timestamp + 86400))
  position <- sim_exchange_positions(exchange)
  account <- sim_exchange_account(exchange)
  expect_equal(position$ctr_unit, expected$units)
  expect_equal(account$cash, expected$cash)
  expect_equal(account$equity, expected$equity)
  expect_equal(sim_exchange_orders(exchange)$status, "filled")
  expect_equal(nrow(exchange$step_events), 1L)
  expect_equal(nrow(exchange$profile_cash_ledger), 1L)
})

test_that("heterogeneous inventory adapter preserves GTC limits and cancels IOC limits", {
  exchange <- sim_exchange_new(list(cash = 1000))
  sim_asset_add(exchange, "SPY", asset_id = 1L, instrument_profile = "etf")
  day1 <- as.POSIXct("2025-01-01", tz = "UTC")
  gtc <- sim_exchange_place_order(exchange, "alice", day1, symbol = "SPY", side = "buy", qty = 1,
    order_type = "limit", limit_price = 90, time_in_force = "gtc")
  ioc <- sim_exchange_place_order(exchange, "bob", day1, symbol = "SPY", side = "buy", qty = 1,
    order_type = "limit", limit_price = 90, time_in_force = "ioc")
  bar <- data.frame(timestamp = day1, symbol = "SPY", asset_id = 1L, open = 100, high = 101, low = 95, close = 100)
  sim_exchange_step(exchange, bar)
  sim_exchange_step(exchange, transform(bar, timestamp = timestamp + 86400))
  orders <- sim_exchange_orders(exchange)
  expect_identical(orders[order_id == gtc, status], "accepted")
  expect_identical(orders[order_id == ioc, status], "cancelled")
  sim_exchange_step(exchange, transform(bar, timestamp = timestamp + 2 * 86400, low = 89))
  expect_identical(sim_exchange_orders(exchange)[order_id == gtc, status], "filled")
  expect_equal(sim_exchange_orders(exchange)[order_id == gtc, price], 90)
})

test_that("heterogeneous inventory adapter rolls back an explicit atomic group", {
  exchange <- sim_exchange_new(list(cash = 100))
  sim_asset_add(exchange, "SPY", asset_id = 1L, instrument_profile = "equity")
  sim_asset_add(exchange, "TLT", asset_id = 2L, instrument_profile = "etf")
  day1 <- as.POSIXct("2025-01-01", tz = "UTC")
  sim_exchange_place_order(exchange, "alice", day1, symbol = "SPY", side = "buy", qty = 1, atomic_group_id = "G1")
  sim_exchange_place_order(exchange, "alice", day1, symbol = "TLT", side = "buy", qty = 1, atomic_group_id = "G1")
  bars <- data.frame(timestamp = c(day1, day1), symbol = c("SPY", "TLT"), asset_id = c(1L, 2L),
    open = c(60, 60), high = c(61, 61), low = c(59, 59), close = c(60, 60))
  sim_exchange_step(exchange, bars)
  sim_exchange_step(exchange, transform(bars, timestamp = timestamp + 86400))
  orders <- sim_exchange_orders(exchange)
  expect_true(all(orders$status == "rejected"))
  expect_true(all(orders$reason_code == "atomic_group_rejected"))
  expect_true(all(sim_exchange_positions(exchange)$ctr_unit == 0))
  expect_equal(sim_exchange_account(exchange)$cash, 100)
})

test_that("heterogeneous inventory adapter preserves sale settlement and state through save/load", {
  exchange <- sim_exchange_new(list(cash = 1000))
  sim_asset_add(exchange, "SPY", asset_id = 1L, instrument_profile = "equity", settlement_lag_days = 1)
  day1 <- as.POSIXct("2025-01-01", tz = "UTC")
  bar <- data.frame(timestamp = day1, symbol = "SPY", asset_id = 1L, open = 100, high = 101, low = 99, close = 100)
  sim_exchange_place_order(exchange, "alice", day1, symbol = "SPY", side = "buy", qty = 2)
  sim_exchange_step(exchange, bar)
  sim_exchange_step(exchange, transform(bar, timestamp = timestamp + 86400))
  sim_exchange_place_order(exchange, "alice", day1 + 86400, symbol = "SPY", side = "sell", qty = 1)
  sim_exchange_step(exchange, transform(bar, timestamp = timestamp + 2 * 86400, open = 110, high = 111, low = 109, close = 110))
  expect_identical(exchange$settlement_ledger$status, "pending")
  path <- tempfile("tradesimr-heterogeneous-inventory-")
  sim_exchange_save(exchange, path)
  restored <- sim_exchange_load(path)
  expect_identical(restored$settlement_ledger$status, "pending")
  sim_exchange_step(restored, transform(bar, timestamp = timestamp + 3 * 86400, open = 110, high = 111, low = 109, close = 110))
  expect_identical(restored$settlement_ledger$status, "settled")
  expect_equal(sim_exchange_positions(restored)$ctr_unit, 1)
})

test_that("mixed-profile target rebalances use one heterogeneous atomic group", {
  exchange <- sim_exchange_new(list(cash = 10000, portfolio_margin = TRUE, lev = 1))
  sim_asset_add(exchange, "SPY", asset_id = 1L, instrument_profile = "equity")
  sim_asset_add(exchange, "ES", asset_id = 2L, instrument_profile = "future")
  execution <- sim_portfolio_execution(fee_rt = 0, lev = 1)
  day1 <- as.POSIXct("2025-01-01", tz = "UTC")
  bars <- data.frame(
    timestamp = rep(day1, 2L), symbol = c("SPY", "ES"), asset_id = c(1L, 2L),
    open = c(100, 100), high = c(101, 101), low = c(99, 99), close = c(100, 100)
  )
  submitted <- sim_portfolio_target_step(exchange, "arena", bars, c(SPY = 0.5, ES = 0.5), execution)
  expect_true(all(submitted$orders$status == "accepted"))
  expect_true(length(unique(submitted$orders$atomic_group_id)) == 1L)

  next_bars <- transform(bars, timestamp = timestamp + 86400)
  filled <- sim_portfolio_target_step(exchange, "arena", next_bars, NULL, execution)
  orders <- sim_exchange_orders(exchange)
  expect_true(all(orders$status == "filled"))
  expect_equal(filled$fills$rebalance_id, rep(submitted$rebalance_id, 2L))
  expect_equal(filled$fills$qty, c(50, 50))
  expect_setequal(filled$positions$symbol, c("SPY", "ES"))
  expect_equal(filled$positions$ctr_unit, c(50, 50))
  expect_equal(filled$account$equity, 10000)
})

test_that("fully paid inventory target weights reject short exposure", {
  exchange <- sim_exchange_new(list(cash = 10000, portfolio_margin = TRUE))
  sim_asset_add(exchange, "SPY", asset_id = 1L, instrument_profile = "equity")
  sim_asset_add(exchange, "ES", asset_id = 2L, instrument_profile = "future")
  bar <- data.frame(
    timestamp = rep(as.POSIXct("2025-01-01", tz = "UTC"), 2L), symbol = c("SPY", "ES"), asset_id = c(1L, 2L),
    open = c(100, 100), high = c(101, 101), low = c(99, 99), close = c(100, 100)
  )
  result <- sim_portfolio_target_step(exchange, "arena", bar, c(SPY = -0.5), allowed_symbols = c("SPY", "ES"))
  expect_identical(result$outcomes$status, "rejected")
  expect_match(result$outcomes$message, "non-negative")
  expect_equal(nrow(sim_exchange_orders(exchange)), 0L)
})
