test_that("FX cash conversion and non-base spot inventory use durable balances", {
  exchange <- sim_exchange_new(list(cash = 1000, base_currency = "USD"))
  sim_exchange_fx_rate(exchange, "USD", "EUR", 0.8, as.POSIXct("2025-01-01", tz = "UTC"))
  sim_exchange_convert_cash(exchange, "alice", 125, "USD", "EUR")
  sim_asset_add(exchange, "SAP", asset_id = 1L, instrument_profile = "equity", quote_ccy = "EUR")
  sim_exchange_place_order(exchange, "alice", as.POSIXct("2025-01-01", tz = "UTC"), symbol = "SAP", side = "buy", qty = 1)
  sim_exchange_step(exchange, data.frame(timestamp = as.POSIXct("2025-01-01", tz = "UTC"),
    symbol = "SAP", asset_id = 1L, open = 50, high = 51, low = 49, close = 50))
  sim_exchange_step(exchange, data.frame(timestamp = as.POSIXct("2025-01-02", tz = "UTC"),
    symbol = "SAP", asset_id = 1L, open = 50, high = 51, low = 49, close = 50))
  balances <- sim_exchange_cash_balances(exchange, "alice")
  expect_equal(balances[currency == "EUR", amount], 50)
  expect_equal(sim_exchange_positions(exchange)$ctr_unit, 1)
  expect_true(nrow(exchange$profile_cash_ledger) >= 3)
  path <- tempfile("tradesimr-profile-")
  sim_exchange_save(exchange, path)
  restored <- sim_exchange_load(path)
  restored_balances <- sim_exchange_cash_balances(restored, "alice")
  expect_equal(restored_balances[currency == "USD", amount], 875)
  expect_equal(restored_balances[currency == "EUR", amount], 50)
})

test_that("spot sales settle on the profile settlement calendar and corporate actions are durable", {
  exchange <- sim_exchange_new(list(cash = 1000))
  sim_asset_add(exchange, "SPY", asset_id = 1L, instrument_profile = "equity", quote_ccy = "USD", settlement_lag_days = 1)
  day1 <- as.POSIXct("2025-01-01", tz = "UTC")
  sim_exchange_place_order(exchange, "alice", day1, symbol = "SPY", side = "buy", qty = 2)
  sim_exchange_step(exchange, data.frame(timestamp = day1, symbol = "SPY", asset_id = 1L, open = 100, high = 101, low = 99, close = 100))
  sim_exchange_step(exchange, data.frame(timestamp = day1 + 86400, symbol = "SPY", asset_id = 1L, open = 100, high = 101, low = 99, close = 100))
  sim_exchange_place_order(exchange, "alice", day1 + 86400, symbol = "SPY", side = "sell", qty = 1)
  sim_exchange_step(exchange, data.frame(timestamp = day1 + 86400, symbol = "SPY", asset_id = 1L, open = 110, high = 111, low = 109, close = 110))
  sim_exchange_step(exchange, data.frame(timestamp = day1 + 2 * 86400, symbol = "SPY", asset_id = 1L, open = 110, high = 111, low = 109, close = 110))
  expect_equal(sim_exchange_cash_balances(exchange, "alice")$amount, 800)
  expect_identical(exchange$settlement_ledger$status, "pending")
  sim_exchange_corporate_action(exchange, "SPY", "dividend", 2, day1 + 3 * 86400)
  sim_exchange_step(exchange, data.frame(timestamp = day1 + 3 * 86400, symbol = "SPY", asset_id = 1L, open = 110, high = 111, low = 109, close = 110))
  expect_equal(sim_exchange_cash_balances(exchange, "alice")$amount, 912)
  expect_identical(exchange$settlement_ledger$status, "settled")
  expect_identical(exchange$corporate_actions$status, "applied")
})

test_that("typed cash balances retain settled and unsettled cash through settlement and load", {
  exchange <- sim_exchange_new(list(cash = 1000, base_currency = "USD"))
  sim_asset_add(exchange, "SAP", asset_id = 1L, instrument_profile = "equity",
    quote_ccy = "EUR", settlement_lag_days = 1)
  sim_exchange_fx_rate(exchange, "USD", "EUR", 0.8, as.POSIXct("2025-01-01", tz = "UTC"))
  sim_exchange_convert_cash(exchange, "alice", 250, "USD", "EUR")
  day_1 <- as.POSIXct("2025-01-01", tz = "UTC")
  bar <- data.frame(timestamp = day_1, symbol = "SAP", asset_id = 1L,
    open = 50, high = 51, low = 49, close = 50)
  sim_exchange_place_order(exchange, "alice", day_1, symbol = "SAP", side = "buy", qty = 2)
  sim_exchange_step(exchange, bar)
  sim_exchange_step(exchange, transform(bar, timestamp = timestamp + 86400))
  sim_exchange_place_order(exchange, "alice", day_1 + 86400, symbol = "SAP", side = "sell", qty = 1)
  sim_exchange_step(exchange, transform(bar, timestamp = timestamp + 2 * 86400))

  typed <- exchange$cash_balances[agent_id == "alice" & currency == "EUR"]
  expect_equal(typed$settled, 100)
  expect_equal(typed$unsettled, 50)
  public <- sim_exchange_cash_balances(exchange, "alice")[currency == "EUR"]
  expect_equal(public$amount, 100)
  expect_equal(public$unsettled, 50)

  path <- tempfile("tradesimr-typed-cash-")
  sim_exchange_save(exchange, path)
  restored <- sim_exchange_load(path)
  expect_equal(restored$cash_balances[agent_id == "alice" & currency == "EUR", settled], 100)
  expect_equal(restored$cash_balances[agent_id == "alice" & currency == "EUR", unsettled], 50)
  sim_exchange_settle(restored, day_1 + 3 * 86400)
  settled <- restored$cash_balances[agent_id == "alice" & currency == "EUR"]
  expect_equal(settled$settled, 150)
  expect_equal(settled$unsettled, 0)
})

test_that("spot target submission plans atomically and executes only after its decision bar", {
  exchange <- sim_exchange_new(list(cash = 1000))
  sim_asset_add(exchange, "SPY", asset_id = 1L, instrument_profile = "etf", quote_ccy = "USD", qty_step = 1)
  day1 <- data.frame(timestamp = as.POSIXct("2025-01-01", tz = "UTC"), symbol = "SPY", asset_id = 1L, open = 100, high = 101, low = 99, close = 100)
  sim_exchange_step(exchange, day1)
  submitted <- sim_spot_target_submit(exchange, "alice", day1, c(SPY = 1))
  expect_identical(submitted$status, "accepted")
  expect_identical(sim_exchange_orders(exchange)$status, "accepted")
  sim_exchange_step(exchange, transform(day1, timestamp = timestamp + 86400, open = 100, high = 101, low = 99, close = 100))
  expect_equal(sim_exchange_positions(exchange)$ctr_unit, 10)
  expect_identical(sim_exchange_orders(exchange)$status, "filled")
})
