// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// backtest_rcpp
Rcpp::NumericVector backtest_rcpp(const Rcpp::NumericVector& timestamp, const Rcpp::NumericVector& open, const Rcpp::NumericVector& high, const Rcpp::NumericVector& low, const Rcpp::NumericVector& close, const Rcpp::NumericVector& tgt_pos, const Rcpp::IntegerVector& pos_strat, const Rcpp::NumericVector& tol_pos, int strat, int asset, double init_cash, double ctr_size, double ctr_step, double lev, double fee_rt, double fund_rt, double mmr, bool rec);
RcppExport SEXP _tradesimr_backtest_rcpp(SEXP timestampSEXP, SEXP openSEXP, SEXP highSEXP, SEXP lowSEXP, SEXP closeSEXP, SEXP tgt_posSEXP, SEXP pos_stratSEXP, SEXP tol_posSEXP, SEXP stratSEXP, SEXP assetSEXP, SEXP init_cashSEXP, SEXP ctr_sizeSEXP, SEXP ctr_stepSEXP, SEXP levSEXP, SEXP fee_rtSEXP, SEXP fund_rtSEXP, SEXP mmrSEXP, SEXP recSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type timestamp(timestampSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type open(openSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type high(highSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type low(lowSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type close(closeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type tgt_pos(tgt_posSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type pos_strat(pos_stratSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type tol_pos(tol_posSEXP);
    Rcpp::traits::input_parameter< int >::type strat(stratSEXP);
    Rcpp::traits::input_parameter< int >::type asset(assetSEXP);
    Rcpp::traits::input_parameter< double >::type init_cash(init_cashSEXP);
    Rcpp::traits::input_parameter< double >::type ctr_size(ctr_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type ctr_step(ctr_stepSEXP);
    Rcpp::traits::input_parameter< double >::type lev(levSEXP);
    Rcpp::traits::input_parameter< double >::type fee_rt(fee_rtSEXP);
    Rcpp::traits::input_parameter< double >::type fund_rt(fund_rtSEXP);
    Rcpp::traits::input_parameter< double >::type mmr(mmrSEXP);
    Rcpp::traits::input_parameter< bool >::type rec(recSEXP);
    rcpp_result_gen = Rcpp::wrap(backtest_rcpp(timestamp, open, high, low, close, tgt_pos, pos_strat, tol_pos, strat, asset, init_cash, ctr_size, ctr_step, lev, fee_rt, fund_rt, mmr, rec));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tradesimr_backtest_rcpp", (DL_FUNC) &_tradesimr_backtest_rcpp, 18},
    {NULL, NULL, 0}
};

RcppExport void R_init_tradesimr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
