// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// backtest_rcpp
Rcpp::List backtest_rcpp(const Rcpp::NumericVector& timestamp, const Rcpp::NumericVector& open, const Rcpp::NumericVector& high, const Rcpp::NumericVector& low, const Rcpp::NumericVector& close, const Rcpp::NumericVector& tgt_pos, const Rcpp::IntegerVector& pos_strat, const Rcpp::NumericVector& tol_pos, const Rcpp::IntegerVector& order_type, const Rcpp::NumericVector& limit_price, int strat, int asset, double init_cash, double ctr_size, double ctr_step, double lev, double fee_rt, double maker_fee_rt, double taker_fee_rt, double fund_rt, double funding_interval_hours, double mmr, int fill_model, double slippage, double spread, bool rec);
RcppExport SEXP _tradesimr_backtest_rcpp(SEXP timestampSEXP, SEXP openSEXP, SEXP highSEXP, SEXP lowSEXP, SEXP closeSEXP, SEXP tgt_posSEXP, SEXP pos_stratSEXP, SEXP tol_posSEXP, SEXP order_typeSEXP, SEXP limit_priceSEXP, SEXP stratSEXP, SEXP assetSEXP, SEXP init_cashSEXP, SEXP ctr_sizeSEXP, SEXP ctr_stepSEXP, SEXP levSEXP, SEXP fee_rtSEXP, SEXP maker_fee_rtSEXP, SEXP taker_fee_rtSEXP, SEXP fund_rtSEXP, SEXP funding_interval_hoursSEXP, SEXP mmrSEXP, SEXP fill_modelSEXP, SEXP slippageSEXP, SEXP spreadSEXP, SEXP recSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type timestamp(timestampSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type open(openSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type high(highSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type low(lowSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type close(closeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type tgt_pos(tgt_posSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type pos_strat(pos_stratSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type tol_pos(tol_posSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type order_type(order_typeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type limit_price(limit_priceSEXP);
    Rcpp::traits::input_parameter< int >::type strat(stratSEXP);
    Rcpp::traits::input_parameter< int >::type asset(assetSEXP);
    Rcpp::traits::input_parameter< double >::type init_cash(init_cashSEXP);
    Rcpp::traits::input_parameter< double >::type ctr_size(ctr_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type ctr_step(ctr_stepSEXP);
    Rcpp::traits::input_parameter< double >::type lev(levSEXP);
    Rcpp::traits::input_parameter< double >::type fee_rt(fee_rtSEXP);
    Rcpp::traits::input_parameter< double >::type maker_fee_rt(maker_fee_rtSEXP);
    Rcpp::traits::input_parameter< double >::type taker_fee_rt(taker_fee_rtSEXP);
    Rcpp::traits::input_parameter< double >::type fund_rt(fund_rtSEXP);
    Rcpp::traits::input_parameter< double >::type funding_interval_hours(funding_interval_hoursSEXP);
    Rcpp::traits::input_parameter< double >::type mmr(mmrSEXP);
    Rcpp::traits::input_parameter< int >::type fill_model(fill_modelSEXP);
    Rcpp::traits::input_parameter< double >::type slippage(slippageSEXP);
    Rcpp::traits::input_parameter< double >::type spread(spreadSEXP);
    Rcpp::traits::input_parameter< bool >::type rec(recSEXP);
    rcpp_result_gen = Rcpp::wrap(backtest_rcpp(timestamp, open, high, low, close, tgt_pos, pos_strat, tol_pos, order_type, limit_price, strat, asset, init_cash, ctr_size, ctr_step, lev, fee_rt, maker_fee_rt, taker_fee_rt, fund_rt, funding_interval_hours, mmr, fill_model, slippage, spread, rec));
    return rcpp_result_gen;
END_RCPP
}
// step_rcpp
Rcpp::List step_rcpp(const Rcpp::List& state, double timestamp, double open, double high, double low, double close, const Rcpp::IntegerVector& action, const Rcpp::IntegerVector& dir, const Rcpp::IntegerVector& order_type, const Rcpp::NumericVector& ctr_qty, const Rcpp::NumericVector& price, const Rcpp::IntegerVector& strat_id, const Rcpp::IntegerVector& action_id, const Rcpp::LogicalVector& fee_aware_target, int asset, double ctr_size, double ctr_step, double lev, double fee_rt, double maker_fee_rt, double taker_fee_rt, double fund_rt, double funding_interval_hours, double mmr, double old_timestamp, double slippage, double spread, bool rec);
RcppExport SEXP _tradesimr_step_rcpp(SEXP stateSEXP, SEXP timestampSEXP, SEXP openSEXP, SEXP highSEXP, SEXP lowSEXP, SEXP closeSEXP, SEXP actionSEXP, SEXP dirSEXP, SEXP order_typeSEXP, SEXP ctr_qtySEXP, SEXP priceSEXP, SEXP strat_idSEXP, SEXP action_idSEXP, SEXP fee_aware_targetSEXP, SEXP assetSEXP, SEXP ctr_sizeSEXP, SEXP ctr_stepSEXP, SEXP levSEXP, SEXP fee_rtSEXP, SEXP maker_fee_rtSEXP, SEXP taker_fee_rtSEXP, SEXP fund_rtSEXP, SEXP funding_interval_hoursSEXP, SEXP mmrSEXP, SEXP old_timestampSEXP, SEXP slippageSEXP, SEXP spreadSEXP, SEXP recSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type state(stateSEXP);
    Rcpp::traits::input_parameter< double >::type timestamp(timestampSEXP);
    Rcpp::traits::input_parameter< double >::type open(openSEXP);
    Rcpp::traits::input_parameter< double >::type high(highSEXP);
    Rcpp::traits::input_parameter< double >::type low(lowSEXP);
    Rcpp::traits::input_parameter< double >::type close(closeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type action(actionSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type dir(dirSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type order_type(order_typeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type ctr_qty(ctr_qtySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type price(priceSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type strat_id(strat_idSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type action_id(action_idSEXP);
    Rcpp::traits::input_parameter< const Rcpp::LogicalVector& >::type fee_aware_target(fee_aware_targetSEXP);
    Rcpp::traits::input_parameter< int >::type asset(assetSEXP);
    Rcpp::traits::input_parameter< double >::type ctr_size(ctr_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type ctr_step(ctr_stepSEXP);
    Rcpp::traits::input_parameter< double >::type lev(levSEXP);
    Rcpp::traits::input_parameter< double >::type fee_rt(fee_rtSEXP);
    Rcpp::traits::input_parameter< double >::type maker_fee_rt(maker_fee_rtSEXP);
    Rcpp::traits::input_parameter< double >::type taker_fee_rt(taker_fee_rtSEXP);
    Rcpp::traits::input_parameter< double >::type fund_rt(fund_rtSEXP);
    Rcpp::traits::input_parameter< double >::type funding_interval_hours(funding_interval_hoursSEXP);
    Rcpp::traits::input_parameter< double >::type mmr(mmrSEXP);
    Rcpp::traits::input_parameter< double >::type old_timestamp(old_timestampSEXP);
    Rcpp::traits::input_parameter< double >::type slippage(slippageSEXP);
    Rcpp::traits::input_parameter< double >::type spread(spreadSEXP);
    Rcpp::traits::input_parameter< bool >::type rec(recSEXP);
    rcpp_result_gen = Rcpp::wrap(step_rcpp(state, timestamp, open, high, low, close, action, dir, order_type, ctr_qty, price, strat_id, action_id, fee_aware_target, asset, ctr_size, ctr_step, lev, fee_rt, maker_fee_rt, taker_fee_rt, fund_rt, funding_interval_hours, mmr, old_timestamp, slippage, spread, rec));
    return rcpp_result_gen;
END_RCPP
}
// portfolio_step_rcpp
Rcpp::List portfolio_step_rcpp(const Rcpp::List& states, const Rcpp::DataFrame& bars, const Rcpp::DataFrame& orders, const Rcpp::NumericMatrix& cov, double shared_cash, double ctr_size, double ctr_step, double lev, double fee_rt, double maker_fee_rt, double taker_fee_rt, double fund_rt, double funding_interval_hours, double mmr, double portfolio_margin_sigma, double portfolio_margin_floor, double old_timestamp, double slippage, double spread, bool rec);
RcppExport SEXP _tradesimr_portfolio_step_rcpp(SEXP statesSEXP, SEXP barsSEXP, SEXP ordersSEXP, SEXP covSEXP, SEXP shared_cashSEXP, SEXP ctr_sizeSEXP, SEXP ctr_stepSEXP, SEXP levSEXP, SEXP fee_rtSEXP, SEXP maker_fee_rtSEXP, SEXP taker_fee_rtSEXP, SEXP fund_rtSEXP, SEXP funding_interval_hoursSEXP, SEXP mmrSEXP, SEXP portfolio_margin_sigmaSEXP, SEXP portfolio_margin_floorSEXP, SEXP old_timestampSEXP, SEXP slippageSEXP, SEXP spreadSEXP, SEXP recSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type states(statesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type bars(barsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type orders(ordersSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type cov(covSEXP);
    Rcpp::traits::input_parameter< double >::type shared_cash(shared_cashSEXP);
    Rcpp::traits::input_parameter< double >::type ctr_size(ctr_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type ctr_step(ctr_stepSEXP);
    Rcpp::traits::input_parameter< double >::type lev(levSEXP);
    Rcpp::traits::input_parameter< double >::type fee_rt(fee_rtSEXP);
    Rcpp::traits::input_parameter< double >::type maker_fee_rt(maker_fee_rtSEXP);
    Rcpp::traits::input_parameter< double >::type taker_fee_rt(taker_fee_rtSEXP);
    Rcpp::traits::input_parameter< double >::type fund_rt(fund_rtSEXP);
    Rcpp::traits::input_parameter< double >::type funding_interval_hours(funding_interval_hoursSEXP);
    Rcpp::traits::input_parameter< double >::type mmr(mmrSEXP);
    Rcpp::traits::input_parameter< double >::type portfolio_margin_sigma(portfolio_margin_sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type portfolio_margin_floor(portfolio_margin_floorSEXP);
    Rcpp::traits::input_parameter< double >::type old_timestamp(old_timestampSEXP);
    Rcpp::traits::input_parameter< double >::type slippage(slippageSEXP);
    Rcpp::traits::input_parameter< double >::type spread(spreadSEXP);
    Rcpp::traits::input_parameter< bool >::type rec(recSEXP);
    rcpp_result_gen = Rcpp::wrap(portfolio_step_rcpp(states, bars, orders, cov, shared_cash, ctr_size, ctr_step, lev, fee_rt, maker_fee_rt, taker_fee_rt, fund_rt, funding_interval_hours, mmr, portfolio_margin_sigma, portfolio_margin_floor, old_timestamp, slippage, spread, rec));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tradesimr_backtest_rcpp", (DL_FUNC) &_tradesimr_backtest_rcpp, 26},
    {"_tradesimr_step_rcpp", (DL_FUNC) &_tradesimr_step_rcpp, 28},
    {"_tradesimr_portfolio_step_rcpp", (DL_FUNC) &_tradesimr_portfolio_step_rcpp, 20},
    {NULL, NULL, 0}
};

RcppExport void R_init_tradesimr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
