# data.table evaluates column names at runtime. Declare the package's
# non-standard-evaluation symbols so R CMD check can distinguish them from
# missing lexical bindings.
utils::globalVariables(c(
  ".", ".I", ".N", ".SD", ":=", ".execution_priority",
  ".position_priority", ".severity",
  "abs_notional", "accounting_model", "accrual_day_count",
  "accrued_interest", "action", "action_id", "action_type", "agent_id",
  "agent_type", "allocation",
  "amount", "asset_class", "asset_class_allocation", "asset_i",
  "asset_i_index", "asset_id", "asset_j", "asset_j_index", "asset_key",
  "atomic_group_id", "average_cost", "bar_close", "bar_stage", "cadence_ok",
  "calendar_open", "cash", "cash_effect", "concentration_hhi",
  "contract_size", "coupon_frequency", "coupon_rate", "ctr_qty", "ctr_unit",
  "currency", "current_signed_qty", "current_signed_quantity", "datetime",
  "decision_equity", "decision_price", "decision_timestamp", "delta_qty",
  "delta_units", "desired_signed_qty", "direction", "drawdown", "drift",
  "due_timestamp", "effective_timestamp", "eligible_after", "equity",
  "equity_component", "event_id", "event_type", "event_type_label", "execution_quality",
  "expected_notional", "expected_signed_quantity", "face_value",
  "factor_exposure", "fee", "fee_aware_target", "fill_id", "filled_orders", "funding_fee",
  "high", "instrument_profile", "intended_action", "intended_dir",
  "is_completed", "is_tradable", "issue_timestamp", "label",
  "last_accrual_timestamp", "last_price", "last_px", "leverage", "limit_price",
  "log_close", "low", "maintenance_margin", "maintenance_rate", "market_value",
  "maturity_timestamp", "next_coupon_timestamp", "notional", "notional_deviation",
  "old_timestamp", "order_id", "order_type", "outcome_message", "outcome_status",
  "peak", "portfolio_vol", "pos_dir", "price", "qty", "qty_step", "qty_type",
  "quantity_deviation", "quote_ccy", "ranking_equity", "realized_notional", "reason_code",
  "realized_signed_quantity", "realized_weight", "realized_weight_before",
  "rebalance_id", "ret", "risk_contribution", "schedule_type", "session_date",
  "session_open", "settled", "settled_base", "settlement_price",
  "settlement_timestamp", "side", "signed_qty", "signed_units", "status",
  "supersedes_rebalance_id", "symbol", "target_derived", "target_weight",
  "timestamp", "total_abs_notional", "total_base", "unrealized_pnl", "unsettled",
  "unsettled_base", "vol", "weight_deviation"
), package = "tradesimr")
