# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

backtest_rcpp <- function(timestamp, open, high, low, close, tgt_pos, pos_strat, tol_pos, strat, asset, init_cash = 10000.0, ctr_size = 1.0, ctr_step = 1.0, lev = 10.0, fee_rt = 0.0, fund_rt = 0.0, mmr = 0.02, rec = FALSE) {
    .Call(`_tradesimr_backtest_rcpp`, timestamp, open, high, low, close, tgt_pos, pos_strat, tol_pos, strat, asset, init_cash, ctr_size, ctr_step, lev, fee_rt, fund_rt, mmr, rec)
}

